[workspace.package]
description = "A simple tool for creating modern online books in pure typst."
authors = ["shiroa Developers"]
version = "0.1.5"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/Myriad-Dreamin/shiroa"
repository = "https://github.com/Myriad-Dreamin/shiroa"


[workspace]
resolver = "2"
members = ["cli", "tools/build-from-source"]

[profile.release]
opt-level = 3
lto = "fat"
debug = false
strip = true

[profile.relwithdebinfo]
inherits = "release"
lto = "thin"
debug = true
strip = false

[workspace.dependencies]

typst = "0.11.1"
typst-assets = "0.11.1"
reflexo-typst = { version = "0.5.0-rc7" }
reflexo-vec2svg = { version = "0.5.0-rc7", features = [
    "experimental-ligature",
] }

handlebars = "4.5"

# general
anyhow = "1"
comemo = "0.4"
tokio = { version = "1.36", features = ["full"] }

# cryptography and processing
serde = { version = "1" }
serde_json = "1"
toml = "0.8"

# web
warp = { version = "0.3", features = ["compression"] }

# cli
clap = { version = "4.5", features = ["derive", "env", "unicode", "wrap_help"] }
clap_complete = "4.5"
clap_complete_fig = "4.5"

# logging and tracing
env_logger = "0.11"
log = "0.4.21"

# misc
vergen = { version = "8.2.5", features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
] }
include_dir = "0.7.3"
pathdiff = "0.2.1"

[patch.crates-io]
typst = { git = "https://github.com/Myriad-Dreamin/typst.git", branch = "typst.ts-v0.11.1-content-hint" }
typst-syntax = { git = "https://github.com/Myriad-Dreamin/typst.git", branch = "typst.ts-v0.11.1-content-hint" }
reflexo-vec2svg = { git = "https://github.com/Myriad-Dreamin/typst.ts", tag = "v0.5.0-rc7", package = "reflexo-vec2svg" }
reflexo-typst = { git = "https://github.com/Myriad-Dreamin/typst.ts", tag = "v0.5.0-rc7", package = "reflexo-typst" }

# typst = { path = "../../../typst/crates/typst" }
# typst-syntax = { path = "../../../typst/crates/typst-syntax" }
# reflexo-vec2svg = { path = "../../exporter/svg" }
# reflexo-typst = { path = "../../core" }
